### ISSUE TITLE
Bucket name with underscore

### ISSUE THREAD

**Issue by caprasadrajmane** [svidela/flask-googlestorage#30]
When creating Bucket object we have to specify name without underscore. We can create bucket names on google cloud with underscore. So why such validation is created?

**Comment by svidela** [comment]
The name of Bucket instances (https://github.com/svidela/flask-googlestorage/blob/master/flask_googlestorage/buckets.py#L233) is not the name of the corresponding Google storage bucket (https://cloud.google.com/storage/docs/buckets#naming). You need to define a configuration variable to connect the two

```python
files = Bucket("files"). # Bucket instance named 'files'
storage = GoogleStorage(files)

def create_app():
    app = Flask(__name__)
    app.config.update(
        GOOGLE_STORAGE_LOCAL_DEST = app.instance_path,
        GOOGLE_STORAGE_FILES_BUCKET = "files-bucket-id". # Google Storage bucket related to the Bucket named 'files'
    )
    storage.init_app(app)

    return app
```

**Comment by caprasadrajmane** [comment]
Thank for the clarification.
